### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by stevepeak**
Debugging coverage, please do not merge. Thanks!

### CODE REVIEW

**Comment by stevepeak** [comment]
Look like no coverage reports were generated: https://travis-ci.org/piratpartiet/drywall/jobs/110654356#L773

Are you able to get them generated locally?

https://github.com/codecov/example-node

**Comment by stevepeak** [comment]
cc @asbjornu

**Comment by asbjornu** [comment]
@stevepeak Thanks for looking into this! After running:

``` shell
$ npm install -g istanbul
$ npm install -g codecov
```

I got to run `instabul cover`, but it fails:

``` shell
$ istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
No coverage information was collected, exit without writing coverage information
./Drywall/node_modules/mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (./Drywall/node_modules/mocha/lib/utils.js:628:15)
    at ./Drywall/node_modules/mocha/bin/_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (./Drywall/node_modules/mocha/bin/_mocha:325:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at runFn (/usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /usr/local/lib/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1613:14)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

Where it gets the `test` path from, I don't know. A default, perhaps? Changing it to the following, I made some progress:

``` shell
$ istanbul cover ./node_modules/mocha/bin/_mocha specs --report lcovonly -- -R spec
```

But now, it runs the tests without `NODE_ENV=test` (see `package.json` for how it's run there), so I added that:

``` shell
$ NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha specs --report lcovonly -- -R spec
```

And now 8 tests pass and code coverage is collected:

``` shell
=============================================================================
Writing coverage object [/Users/bitbear/Dropbox/Dev/Drywall/coverage/coverage.json]
Writing coverage reports at [/Users/bitbear/Dropbox/Dev/Drywall/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 22.07% ( 543/2460 )
Branches     : 8.77% ( 95/1083 )
Functions    : 13.12% ( 77/587 )
Lines        : 22.07% ( 543/2460 )
================================================================================
```

However, 5 tests are failing with the following exception:

``` shell
     Error: Module version mismatch. Expected 47, got 46.
      at Error (native)
      at bindings (node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
      at Object.<anonymous> (node_modules/bcrypt/bcrypt.js:3:35)
      at Object.Module._extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/istanbul/lib/hook.js:109:37)
      at sequelize.define.classMethods.encryptPassword (models/User.js:9:1891)
      at createUser (specs/login.js:9:1527)
      at Context.<anonymous> (specs/login.js:9:6598)
```

Any idea how I can fix this?

**Comment by stevepeak** [comment]
@asbjornu I have not see these issues before. Sorry :( 

Did you see this SO: http://stackoverflow.com/questions/15584529/module-version-mismatch-expected-11-got-1

**Comment by asbjornu** [comment]
@stevepeak Thanks for the help, it seems like I have something working in 528eadcbcf7e29cfbd7bb343570303baf96431e7.

**Pull request closed without merging**
